name: Publish Docker Nightly
on:
  push:
    branches:
      - master
  release:
    types:
       - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8]
        pytorch_version: [1.1, 1.2, 1.3, 1.4, 1.5]
    steps:
    - name: Publish Master
      # publish master
      uses: elgohr/Publish-Docker-Github-Action@2.14
      if: github.event_name == 'push'
      with:
        name: pytorchlightning/pytorch_lightning
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        buildargs: PYTHON_VERSION=${{ matrix.python_version }},PYTORCH_VERSION=${{ matrix.pytorch_version }},LIGHTNING_VERSION=${{ steps.get_version.outputs.VERSION }}
        tags: "nightly-py${{ matrix.python_version }}-torch${{ matrix.pytorch_version }}"
